import Link from 'next/link';
import { notFound } from 'next/navigation';
import Footer from '@/components/Footer';
import { getService, services } from '@/lib/services';
import { siteUrl } from '@/lib/site';
import './service.css';

export function generateStaticParams() { return services.map(({ slug }) => ({ slug })); }
export async function generateMetadata({ params }) { const service = getService((await params).slug); if (!service) return {}; return { title: `${service.title} | Công ty Luật Trần Á`, description: service.description, alternates: { canonical: `${siteUrl}/linh-vuc/${service.slug}` }, openGraph: { title: service.title, description: service.description, images: [service.image] } }; }
export default async function ServicePage({ params }) {
  const service = getService((await params).slug); if (!service) notFound();
  const related = services.filter(item => item.slug !== service.slug).slice(0, 3);
  const crumbs = { '@context': 'https://schema.org', '@type': 'BreadcrumbList', itemListElement: [{ '@type':'ListItem', position:1, name:'Trang chủ', item:siteUrl }, { '@type':'ListItem', position:2, name:'Lĩnh vực', item:`${siteUrl}/#services` }, { '@type':'ListItem', position:3, name:service.title, item:`${siteUrl}/linh-vuc/${service.slug}` }] };
  return <><main className="service-page"><div className="service-topbar container"><Link href="/" className="service-brand"><img src="/logo.svg" alt="" /> Công ty Luật Trần Á</Link><a href="tel:0918439995">0918.439.995</a></div><section className="service-hero"><div className="container"><nav aria-label="Breadcrumb"><Link href="/">Trang chủ</Link><span>/</span><Link href="/#services">Lĩnh vực</Link><span>/</span><span>{service.shortTitle}</span></nav><div><span className="section-tag">LĨNH VỰC {service.number}</span><h1>{service.title}</h1><p>{service.description}</p><a className="btn btn-gold" href="#service-contact">Trao đổi với luật sư <span>↗</span></a></div></div><img src={service.image} alt={`Dịch vụ ${service.title} tại Luật Trần Á`} /></section><section className="service-overview container"><div><span className="section-tag">PHẠM VI HỖ TRỢ</span><h2>Đi cùng khách hàng từ đánh giá ban đầu đến quá trình giải quyết.</h2></div><ol>{service.issues.map((item,index)=><li key={item}><span>0{index+1}</span>{item}</li>)}</ol></section><section className="service-preparation"><div className="container"><div><span className="section-tag">HỒ SƠ BAN ĐẦU</span><h2>Tài liệu khách hàng nên chuẩn bị</h2><p>Danh mục có thể thay đổi theo tính chất vụ việc. Luật sư sẽ hướng dẫn cụ thể sau khi tiếp nhận thông tin.</p></div><ul>{service.documents.map((item,index)=><li key={item}><span>{index+1}</span>{item}</li>)}</ul></div></section><section className="service-faq container"><header><span className="section-tag">QUY TRÌNH</span><h2>Ba bước làm việc rõ ràng</h2></header>{[['Tiếp nhận và bảo mật thông tin','Luật sư lắng nghe nhu cầu, rà soát tài liệu ban đầu và xác định phạm vi cần hỗ trợ.'],['Phân tích và thống nhất phương án','Trao đổi hướng xử lý, công việc, thời gian dự kiến và chi phí trước khi triển khai.'],['Đồng hành trong quá trình giải quyết','Thực hiện công việc đã thống nhất, cập nhật tiến độ và tư vấn các quyết định phát sinh.']].map(([title,body],index)=><details key={title} open={index===0}><summary><span>0{index+1}</span>{title}</summary><p>{body}</p></details>)}</section><section className="service-related container"><span className="section-tag">LĨNH VỰC LIÊN QUAN</span><div>{related.map(item=><Link href={`/linh-vuc/${item.slug}`} key={item.slug}><span>{item.number}</span>{item.shortTitle}<i>↗</i></Link>)}</div></section><section id="service-contact" className="service-cta"><div className="container"><span>YOUR RIGHTS. OUR COMMITMENT.</span><h2>Bắt đầu từ một cuộc trao đổi bảo mật.</h2><p>Mỗi vụ việc có bối cảnh riêng. Luật sư Trần Á sẽ lắng nghe và định hướng trên hồ sơ cụ thể.</p><a href="tel:0918439995">Gọi 0918.439.995 <span>↗</span></a></div></section><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(crumbs).replace(/</g,'\\u003c')}} /></main><Footer /></>;
}
