export const services = [
  { slug: 'tranh-tung-toa-an', number: '01', title: 'Tham Dự Toà Án & Tranh Tụng', shortTitle: 'Tranh tụng & Tòa án', image: '/court-litigation.png', description: 'Đại diện, bảo vệ quyền và lợi ích hợp pháp tại các cấp Tòa án và Trung tâm Trọng tài.', issues: ['Tranh tụng dân sự, đất đai và kinh doanh thương mại', 'Đại diện tố tụng tại Tòa án và Trung tâm Trọng tài', 'Soạn đơn khởi kiện, bản tự khai và yêu cầu phản tố', 'Phân tích chứng cứ và xây dựng phương án bảo vệ'], documents: ['Tài liệu nhân thân hoặc pháp nhân', 'Hợp đồng, giấy tờ và trao đổi liên quan', 'Chứng cứ, biên bản và quyết định đã có'] },
  { slug: 'dat-dai-bat-dong-san', number: '02', title: 'Đất Đai & Bất Động Sản', shortTitle: 'Đất đai & Bất động sản', image: '/land-service.png', description: 'Tư vấn thủ tục đất đai và giải quyết tranh chấp về quyền sử dụng đất, nhà ở và bồi thường.', issues: ['Tranh chấp đất đai tại UBND và Tòa án', 'Cấp mới, sang tên và chuyển mục đích sử dụng', 'Tách thửa, hợp thửa và thừa kế nhà đất', 'Khiếu kiện quyết định cấp giấy chứng nhận'], documents: ['Giấy chứng nhận hoặc giấy tờ nguồn gốc đất', 'Hồ sơ địa chính, đo đạc và hiện trạng', 'Biên bản hòa giải và quyết định hành chính'] },
  { slug: 'bao-chua-hinh-su', number: '03', title: 'Bào Chữa Án Hình Sự', shortTitle: 'Hình sự', image: '/legal-library.jpg', description: 'Bảo vệ người bị tạm giữ, bị can, bị cáo và người bị hại trong các giai đoạn tố tụng.', issues: ['Tham gia lấy lời khai và đối chất', 'Thu thập chứng cứ gỡ tội và tình tiết giảm nhẹ', 'Bào chữa tại phiên tòa hình sự', 'Bảo vệ quyền lợi của người bị hại'], documents: ['Giấy triệu tập, quyết định tố tụng', 'Tài liệu nhân thân và tình tiết giảm nhẹ', 'Chứng cứ, dữ liệu và thông tin người làm chứng'] },
  { slug: 'dan-su-thua-ke', number: '04', title: 'Dân Sự & Thừa Kế', shortTitle: 'Dân sự & Thừa kế', image: '/office-interior.png', description: 'Giải quyết tranh chấp hợp đồng, vay nợ, bồi thường và phân chia di sản thừa kế.', issues: ['Tranh chấp hợp đồng và đặt cọc', 'Thu hồi nợ và bồi thường thiệt hại', 'Lập di chúc và khai nhận di sản', 'Khởi kiện vụ án dân sự'], documents: ['Hợp đồng và chứng từ giao dịch', 'Di chúc, giấy tờ hộ tịch', 'Tài liệu về tài sản và nghĩa vụ liên quan'] },
  { slug: 'hon-nhan-gia-dinh', number: '05', title: 'Hôn Nhân & Gia Đình', shortTitle: 'Hôn nhân & Gia đình', image: '/office-interior.png', description: 'Tư vấn ly hôn, quyền nuôi con, cấp dưỡng và phân chia tài sản chung vợ chồng.', issues: ['Ly hôn thuận tình và đơn phương', 'Tranh chấp quyền nuôi con và cấp dưỡng', 'Phân chia tài sản và nợ chung', 'Vụ việc có yếu tố nước ngoài'], documents: ['Giấy chứng nhận kết hôn', 'Giấy khai sinh và tài liệu về con', 'Giấy tờ về tài sản, thu nhập và nghĩa vụ'] },
  { slug: 'doanh-nghiep-thuong-mai', number: '06', title: 'Doanh Nghiệp & Thương Mại', shortTitle: 'Doanh nghiệp & Thương mại', image: '/business-architecture.jpg', description: 'Tư vấn pháp lý thường xuyên, rà soát hợp đồng và giải quyết tranh chấp kinh doanh.', issues: ['Tư vấn pháp lý thường xuyên', 'Soạn thảo và rà soát hợp đồng', 'Tranh chấp thành viên góp vốn, cổ đông', 'Trọng tài và tranh chấp thương mại'], documents: ['Hồ sơ pháp lý doanh nghiệp', 'Hợp đồng và phụ lục liên quan', 'Chứng từ giao dịch, biên bản và trao đổi'] },
];

export function getService(slug) { return services.find((service) => service.slug === slug); }
